version: '3'

services:
  maxxinnova.pilotcartracker.manager:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat
